name: Stable Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: cd src && ./gradlew build

      - name: Generate tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d-%H%M%S')"
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Create Stable Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: "Stable Release ${{ steps.tag.outputs.tag_name }}"
          make_latest: true
          body: |
            ### Стабильный релиз
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
